// examples/sveltekit/src/lib/DebateStream.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { getBrowserClient } from './aragora';
  import { connectDebateStream, type StreamEvent } from './debate-stream';

  export let debateId: string;
  let events: StreamEvent[] = [];
  let connected = false;
  let connectionError: string | null = null;

  onMount(() => connectDebateStream(getBrowserClient().createWebSocket(), debateId, {
    onEvent: event => { events = [...events.slice(-199), event]; },
    onConnected: value => { connected = value; },
    onError: value => { connectionError = value; },
  }));
</script>

<p class="connection-status" role="status">
  {connectionError ? `Connection error: ${connectionError}` : connected ? 'Connected' : 'Disconnected'}
</p>

{#if events.length === 0}
  <p>Waiting for events...</p>
{:else}
  <div class="stream-events">
    {#each events as event}
      <div class="stream-event">
        <div class="event-header">
          <strong>{event.type}{#if event.agent} ({event.agent}){/if}</strong>
          {#if event.timestamp}
            <time datetime={event.timestamp}>{new Date(event.timestamp).toLocaleTimeString()}</time>
          {:else}
            <span class="event-time">Time not reported</span>
          {/if}
        </div>
        {#if event.content}
          <p>{event.content.slice(0, 200)}{event.content.length > 200 ? '...' : ''}</p>
        {/if}
      </div>
    {/each}
  </div>
{/if}

<style>
  .connection-status { margin: 0.5rem 0 1rem; }
  .stream-events { max-height: 24rem; overflow-y: auto; }
  .stream-event { padding: 0.75rem 0; border-top: 1px solid var(--border); }
  .event-header { display: flex; flex-wrap: wrap; justify-content: space-between; gap: 0.5rem; }
  time, .event-time { font-size: 0.75rem; color: var(--text-muted); }
</style>

// examples/remix/app/DebateStream.tsx
import { createClient } from '@aragora/sdk';
import { useEffect, useState } from 'react';
import { connectDebateStream, type StreamEvent } from './debate-stream';

export function DebateStream({ debateId }: { debateId: string }) {
  const [events, setEvents] = useState<StreamEvent[]>([]);
  const [connected, setConnected] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    setEvents([]);
    setConnected(false);
    setError(null);
    const stream = createClient({
      baseUrl: import.meta.env.VITE_ARAGORA_API_URL || 'http://localhost:8080',
      wsUrl: import.meta.env.VITE_ARAGORA_WS_URL || undefined,
    }).createWebSocket();
    return connectDebateStream(stream, debateId, {
      onEvent: event => setEvents(previous => [...previous, event].slice(-200)),
      onConnected: setConnected,
      onError: setError,
    });
  }, [debateId]);

  return (
    <div>
      <p style={{ color: connected ? '#86efac' : 'var(--text-muted)', marginBottom: '1rem' }}>
        {connected ? 'Connected' : 'Disconnected'}
      </p>
      {error && <p role="alert">{error}</p>}
      {events.length === 0 ? <p>Waiting for events...</p> : events.map((event, index) => (
        <div key={index} style={{ padding: '0.75rem', borderBottom: '1px solid var(--border)' }}>
          <div className="event-heading">
            <strong>{event.type}{event.agent && ` (${event.agent})`}</strong>
            <span style={{ fontSize: '0.75rem', color: 'var(--text-muted)' }}>
              {event.timestamp
                ? <time dateTime={event.timestamp}>{new Date(event.timestamp).toLocaleTimeString()}</time>
                : 'Time not reported'}
            </span>
          </div>
          {event.content && <p>{event.content.slice(0, 200)}{event.content.length > 200 ? '...' : ''}</p>}
        </div>
      ))}
    </div>
  );
}
